
version: "2"
services:


  elk:
    build:
      context: .
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

  fbeat:
    build:
      context: filebeat
    volumes:
      - ./log.txt:/var/log/nginx/access.log

